### ISSUE TITLE
Can't load dashboard w/ relative host/non default port

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#132]
So when I launch with `localhost` as the host, I am able to access the experiment list and query pages but not the dashboard pages unless I explicitly type my IP or `127.0.0.1`.

Similarly, I'm launching on an external server (not AWS unfortunately), and the NEXT port (out of my control) is not the default 8000.  Again, I can load the experiment list and query pages, but not the dashboard pages.  This happens whether I use the hostname or IP.  Here's the error I get from the backend:

(host ip and port are ***\* because I don't want this info public)

```
nextbackenddocker_1  | [2016-08-25 21:23:45,920] ERROR in app: Exception on /dashboard/experiment_dashboard/8b9f15f802367af69090911aecc0d2/RocketBinaryClassification [GET]
nextbackenddocker_1  | Traceback (most recent call last):
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
nextbackenddocker_1  |     response = self.full_dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
nextbackenddocker_1  |     rv = self.handle_user_exception(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
nextbackenddocker_1  |     reraise(exc_type, exc_value, tb)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
nextbackenddocker_1  |     rv = self.dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
nextbackenddocker_1  |     return self.view_functions[rule.endpoint](**req.view_args)
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 157, in experiment_dashboard
nextbackenddocker_1  |     exceptions_present=exceptions_present(exp_uid, host_url),
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 168, in exceptions_present
nextbackenddocker_1  |     r = requests.get(url)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
nextbackenddocker_1  |     return request('get', url, **kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
nextbackenddocker_1  |     return session.request(method=method, url=url, **kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
nextbackenddocker_1  |     resp = self.send(prep, **send_kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
nextbackenddocker_1  |     r = adapter.send(request, **kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
nextbackenddocker_1  |     raise ConnectionError(e)
nextbackenddocker_1  | ConnectionError: HTTPConnectionPool(host='********', port=******): Max retries exceeded with url: /api/experiment/8b9f15f802367af69090911aecc0d2/logs/APP-EXCEPTION (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)
nextbackenddocker_1  | Exception on /dashboard/experiment_dashboard/8b9f15f802367af69090911aecc0d2/RocketBinaryClassification [GET]
nextbackenddocker_1  | Traceback (most recent call last):
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
nextbackenddocker_1  |     response = self.full_dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
nextbackenddocker_1  |     rv = self.handle_user_exception(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
nextbackenddocker_1  |     reraise(exc_type, exc_value, tb)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
nextbackenddocker_1  |     rv = self.dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
nextbackenddocker_1  |     return self.view_functions[rule.endpoint](**req.view_args)
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 157, in experiment_dashboard
nextbackenddocker_1  |     exceptions_present=exceptions_present(exp_uid, host_url),
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 168, in exceptions_present
nextbackenddocker_1  |     r = requests.get(url)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
nextbackenddocker_1  |     return request('get', url, **kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
nextbackenddocker_1  |     return session.request(method=method, url=url, **kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
nextbackenddocker_1  |     resp = self.send(prep, **send_kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
nextbackenddocker_1  |     r = adapter.send(request, **kwargs)
nextbackenddocker_1  |   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
nextbackenddocker_1  |     raise ConnectionError(e)
nextbackenddocker_1  | ConnectionError: HTTPConnectionPool(host='********', port=******): Max retries exceeded with url: /api/experiment/8b9f15f802367af69090911aecc0d2/logs/APP-EXCEPTION (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)
nextbackenddocker_1  | [2016-08-25 21:23:45 +0000] [11] [DEBUG] Closing connection.
nextbackenddocker_1  | [2016-08-25 21:26:25 +0000] [11] [DEBUG] GET /dashboard/experiment_dashboard/8b9f15f802367af69090911aecc0d2/RocketBinaryClassification

```

I took a quick look around but I don't see anything that would indicate why only the dashboard would be throwing this error and not the other pages.

**Comment by dconathan** [comment]
(clarification: port 8000 is still being used internally for NEXT on the server, that port is being forwarded to another port for external access)

**Comment by dconathan** [comment]
Problem is fixed by bypassing the `exceptions_present` function of [dashboard.py](https://github.com/nextml/NEXT/blob/master/next/dashboard/dashboard.py#L149) (ie just forcing it to return `False`).  Dashboard loads fine now... I guess the `url` getting passed to that `requests.get(url)` is not correct?

**Comment by dconathan** [comment]
Hmmm, interesting.  Dashboard loads fine but no data is loading.  e.g:
Number of participants: 0 
Number of answers: 0 
And no timing data, despite having many labels.
(The dashboard plots specific to my app are loading fine, but I've set it up to load the data in a funny way that bypasses NEXT)

**Comment by kgjamieson** [comment]
I made massive changes to the dashboard that changes the way these resources are retrieved. Merging in this commit should fix everything.. https://github.com/nextml/NEXT/commit/fa5c7d208266d46a3bdf88843092a8036a697fcf

**Comment by dconathan** [comment]
Cool... should've mentioned I'm a bit out of date. I'll let you know.

**Comment by dconathan** [comment]
Just noticed this is a dupe of #161 which has more info.
