### ISSUE TITLE
rename-apps broke backend for me

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#156]
After [155](https://github.com/nextml/NEXT/pull/155) backend doesn't start for me:

```
nextbackenddocker_1  | [2016-12-12 21:04:02 +0000] [12] [ERROR] Exception in worker process
nextbackenddocker_1  | Traceback (most recent call last):
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
nextbackenddocker_1  |     worker.init_process()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 190, in init_process
nextbackenddocker_1  |     super(GeventWorker, self).init_process()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
nextbackenddocker_1  |     self.load_wsgi()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
nextbackenddocker_1  |     self.wsgi = self.app.wsgi()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
nextbackenddocker_1  |     self.callable = self.load()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
nextbackenddocker_1  |     return self.load_wsgiapp()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
nextbackenddocker_1  |     return util.import_app(self.app_uri)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
nextbackenddocker_1  |     __import__(module)
nextbackenddocker_1  |   File "/next_backend/next/api/api.py", line 12, in <module>
nextbackenddocker_1  |     app.register_blueprint(home, url_prefix='/home')
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 65, in wrapper_func
nextbackenddocker_1  |     return f(self, *args, **kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 958, in register_blueprint
nextbackenddocker_1  |     if blueprint.name in self.blueprints:
nextbackenddocker_1  | AttributeError: 'module' object has no attribute 'name'
```

**Comment by dconathan** [comment]
Found the issue... [this](https://github.com/nextml/NEXT/blob/master/next/api/api.py#L4) should be `from next.home.home import home`

**Comment by stsievert** [comment]
I knew something would sneak past. Can you make a pull request for this?

**Comment by dconathan** [comment]
https://github.com/nextml/NEXT/pull/158

**Comment by dconathan** [comment]
Fixed.  It was a `.pyc` issue on my end.
