### ISSUE TITLE
Dashboard won't load with non-8000 port.

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#161]
I've tested this with various ports (8888, 8080, etc.) and getting the same errors every time.  /home, dashboard/experiment_list, and queries pages load fine, but dashboard throws this error:

```
nextbackenddocker_1  | Exception on /dashboard/experiment_dashboard/50f15481fdcf2661da692a155c5a66/RocketClassification [GET]
nextbackenddocker_1  | Traceback (most recent call last):
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
nextbackenddocker_1  |     response = self.full_dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
nextbackenddocker_1  |     rv = self.handle_user_exception(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
nextbackenddocker_1  |     reraise(exc_type, exc_value, tb)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
nextbackenddocker_1  |     rv = self.dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
nextbackenddocker_1  |     return self.view_functions[rule.endpoint](**req.view_args)
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 144, in experiment_dashboard
nextbackenddocker_1  |     exceptions_present=exceptions_present(exp_uid, host_url),
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 152, in exceptions_present
nextbackenddocker_1  |     r = requests.get(url)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
nextbackenddocker_1  |     return request('get', url, params=params, **kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
nextbackenddocker_1  |     return session.request(method=method, url=url, **kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
nextbackenddocker_1  |     resp = self.send(prep, **send_kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
nextbackenddocker_1  |     r = adapter.send(request, **kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
nextbackenddocker_1  |     raise ConnectionError(e, request=request)
nextbackenddocker_1  | ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/experiment/50f15481fdcf2661da692a155c5a66/logs/APP-EXCEPTION (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8f3b8bed10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by dconathan** [comment]
If I bypass the `exceptions_present` function it loads fine... any idea why that `APP-EXCEPTION` url wouldn't work with the new port?

**Comment by dconathan** [comment]
`APP-EXCEPTION` url works though:
```{"meta": {"status": "OK", "code": 200}, "log_data": []}```

**Comment by dconathan** [comment]
Figured it out.  The backend is still using `8000` as a port internally, it's only exposed externally as `8888`/`8080` etc. so it seems like no matter what, that function should be calling `localhost:8000` not the external host/port.

Any idea how isolated this sort of thing is?  Any other possible places for this kind of bug?  I'm just wondering what the easiest fix for this is...

**Comment by dconathan** [comment]
Actually probably just makes the most sense to force the internal ports to mirror the external ports.  I'll submit a pull request that fixes this and should make using the non-default port work out of the box.

**Comment by dconathan** [comment]
After some more testing, it seems that the `host_url` [here](https://github.com/nextml/NEXT/blob/master/next/dashboard/dashboard.py#L150-L152) should *always* be `http://0.0.0.0:8000` (or whatever the backend port is)...

Does anyone think otherwise?  Will this function ever get called from outside the `next_backend` container?

This will change #162 ...

**Comment by liamim** [comment]
The dashboard works fine on non-8000 ports now; I think something in #203 fixed this.
Gunicorn still serves on `8000`; only the Docker port forward is changed.
