### ISSUE TITLE
first launch using ec2 scripts does not succeed

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#34]
Using ec2 scripts to launch NEXT, the containers appear to successfully build but when they're launched I got the following error for nextbackenddocker. Clearly since that fails to launch, all its dependencies also fail. This happens with absolutely no interaction on my part, so it should be easily reproducible. Funny thing is, when I docker_login, remove all the containers (docker rm -fv $(docker ps -a -q)) then do docker-compose up everything works great

```shell
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [1] [DEBUG] Current configuration:
nextbackenddocker_1 |   proxy_protocol: False
nextbackenddocker_1 |   worker_connections: 1000
nextbackenddocker_1 |   statsd_host: None
nextbackenddocker_1 |   max_requests_jitter: 0
nextbackenddocker_1 |   post_fork: <function post_fork at 0x7f172c05a2a8>
nextbackenddocker_1 |   pythonpath: None
nextbackenddocker_1 |   enable_stdio_inheritance: True
nextbackenddocker_1 |   worker_class: gevent
nextbackenddocker_1 |   ssl_version: 3
nextbackenddocker_1 |   suppress_ragged_eofs: True
nextbackenddocker_1 |   syslog: False
nextbackenddocker_1 |   syslog_facility: user
nextbackenddocker_1 |   when_ready: <function when_ready at 0x7f172c053f50>
nextbackenddocker_1 |   pre_fork: <function pre_fork at 0x7f172c05a140>
nextbackenddocker_1 |   cert_reqs: 0
nextbackenddocker_1 |   preload_app: False
nextbackenddocker_1 |   keepalive: 2
nextbackenddocker_1 |   accesslog: None
nextbackenddocker_1 |   group: 0
nextbackenddocker_1 |   graceful_timeout: 30
nextbackenddocker_1 |   do_handshake_on_connect: False
nextbackenddocker_1 |   spew: False
nextbackenddocker_1 |   workers: 5
nextbackenddocker_1 |   proc_name: None
nextbackenddocker_1 |   sendfile: True
nextbackenddocker_1 |   pidfile: None
nextbackenddocker_1 |   umask: 0
nextbackenddocker_1 |   on_reload: <function on_reload at 0x7f172c053de8>
nextbackenddocker_1 |   pre_exec: <function pre_exec at 0x7f172c05a848>
nextbackenddocker_1 |   worker_tmp_dir: None
nextbackenddocker_1 |   post_worker_init: <function post_worker_init at 0x7f172c05a410>
nextbackenddocker_1 |   limit_request_fields: 100
nextbackenddocker_1 |   on_exit: <function on_exit at 0x7f172c05aed8>
nextbackenddocker_1 |   config: None
nextbackenddocker_1 |   secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
nextbackenddocker_1 |   proxy_allow_ips: ['127.0.0.1']
nextbackenddocker_1 |   pre_request: <function pre_request at 0x7f172c05a9b0>
nextbackenddocker_1 |   post_request: <function post_request at 0x7f172c05aaa0>
nextbackenddocker_1 |   user: 0
nextbackenddocker_1 |   forwarded_allow_ips: ['127.0.0.1']
nextbackenddocker_1 |   worker_int: <function worker_int at 0x7f172c05a578>
nextbackenddocker_1 |   threads: 1
nextbackenddocker_1 |   max_requests: 0
nextbackenddocker_1 |   limit_request_line: 4094
nextbackenddocker_1 |   access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
nextbackenddocker_1 |   certfile: None
nextbackenddocker_1 |   worker_exit: <function worker_exit at 0x7f172c05ac08>
nextbackenddocker_1 |   chdir: /next_backend
nextbackenddocker_1 |   paste: None
nextbackenddocker_1 |   default_proc_name: next.api.api:app
nextbackenddocker_1 |   errorlog: -
nextbackenddocker_1 |   loglevel: debug
nextbackenddocker_1 |   logconfig: None
nextbackenddocker_1 |   syslog_addr: udp://localhost:514
nextbackenddocker_1 |   syslog_prefix: None
nextbackenddocker_1 |   daemon: False
nextbackenddocker_1 |   ciphers: TLSv1
nextbackenddocker_1 |   on_starting: <function on_starting at 0x7f172c053c80>
nextbackenddocker_1 |   worker_abort: <function worker_abort at 0x7f172c05a6e0>
nextbackenddocker_1 |   bind: ['0.0.0.0:8000']
nextbackenddocker_1 |   raw_env: []
nextbackenddocker_1 |   reload: True
nextbackenddocker_1 |   check_config: False
nextbackenddocker_1 |   limit_request_field_size: 8190
nextbackenddocker_1 |   nworkers_changed: <function nworkers_changed at 0x7f172c05ad70>
nextbackenddocker_1 |   timeout: 30
nextbackenddocker_1 |   ca_certs: None
nextbackenddocker_1 |   django_settings: None
nextbackenddocker_1 |   tmp_upload_dir: None
nextbackenddocker_1 |   keyfile: None
nextbackenddocker_1 |   backlog: 2048
nextbackenddocker_1 |   logger_class: simple
nextbackenddocker_1 |   statsd_prefix: 
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [1] [INFO] Starting gunicorn 19.3.0
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [1] [DEBUG] Arbiter booted
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [1] [INFO] Using worker: gevent
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [9] [INFO] Booting worker with pid: 9
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [10] [INFO] Booting worker with pid: 10
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [11] [INFO] Booting worker with pid: 11
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [16] [INFO] Booting worker with pid: 16
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [25] [INFO] Booting worker with pid: 25
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [1] [DEBUG] 5 workers
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [11] [ERROR] Exception in worker process:
nextbackenddocker_1 | Traceback (most recent call last):
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
nextbackenddocker_1 |     worker.init_process()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 192, in init_process
nextbackenddocker_1 |     super(GeventWorker, self).init_process()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
nextbackenddocker_1 |     self.wsgi = self.app.wsgi()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
nextbackenddocker_1 |     self.callable = self.load()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
nextbackenddocker_1 |     return self.load_wsgiapp()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
nextbackenddocker_1 |     return util.import_app(self.app_uri)
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
nextbackenddocker_1 |     __import__(module)
nextbackenddocker_1 |   File "/next_backend/next/api/api.py", line 1, in <module>
nextbackenddocker_1 |     from next.api import api_blueprint
nextbackenddocker_1 |   File "/next_backend/next/api/api_blueprint.py", line 39, in <module>
nextbackenddocker_1 |     from next.api.resources.targets import Targets
nextbackenddocker_1 |   File "/next_backend/next/api/resources/targets.py", line 17, in <module>
nextbackenddocker_1 |     from next.api.widgets_library import widgetManager
nextbackenddocker_1 |   File "/next_backend/next/api/widgets_library/__init__.py", line 1, in <module>
nextbackenddocker_1 |     from widget_manager import widgetManager
nextbackenddocker_1 |   File "/next_backend/next/api/widgets_library/widget_manager.py", line 1, in <module>
nextbackenddocker_1 |     import next.apps.TupleBanditsPureExploration.widgets
nextbackenddocker_1 |   File "/next_backend/next/apps/TupleBanditsPureExploration/__init__.py", line 1, in <module>
nextbackenddocker_1 |     from .TupleBanditsPureExploration import *
nextbackenddocker_1 |   File "/next_backend/next/apps/TupleBanditsPureExploration/TupleBanditsPureExploration.py", line 23, in <module>
nextbackenddocker_1 |     from next.apps.TupleBanditsPureExploration.Dashboard import TupleBanditsPureExplorationDashboard
nextbackenddocker_1 |   File "/next_backend/next/apps/TupleBanditsPureExploration/Dashboard.py", line 15, in <module>
nextbackenddocker_1 |     import matplotlib.pyplot as plt
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 24, in <module>
nextbackenddocker_1 |     import matplotlib.colorbar
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/colorbar.py", line 29, in <module>
nextbackenddocker_1 |     import matplotlib.collections as collections
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/collections.py", line 23, in <module>
nextbackenddocker_1 |     import matplotlib.backend_bases as backend_bases
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 50, in <module>
nextbackenddocker_1 |     import matplotlib.textpath as textpath
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/textpath.py", line 11, in <module>
nextbackenddocker_1 |     import matplotlib.font_manager as font_manager
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1356, in <module>
nextbackenddocker_1 |     _rebuild()
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1343, in _rebuild
nextbackenddocker_1 |     pickle_dump(fontManager, _fmcache)
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 939, in pickle_dump
nextbackenddocker_1 |     with open(filename, 'wb') as fh:
nextbackenddocker_1 | IOError: [Errno 2] No such file or directory: '/tmp/matplotlib-root/fontList.cache'
nextbackenddocker_1 | Traceback (most recent call last):
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
nextbackenddocker_1 |     worker.init_process()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 192, in init_process
nextbackenddocker_1 |     super(GeventWorker, self).init_process()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
nextbackenddocker_1 |     self.wsgi = self.app.wsgi()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
nextbackenddocker_1 |     self.callable = self.load()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
nextbackenddocker_1 |     return self.load_wsgiapp()
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
nextbackenddocker_1 |     return util.import_app(self.app_uri)
nextbackenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
nextbackenddocker_1 |     __import__(module)
nextbackenddocker_1 |   File "/next_backend/next/api/api.py", line 1, in <module>
nextbackenddocker_1 |     from next.api import api_blueprint
nextbackenddocker_1 |   File "/next_backend/next/api/api_blueprint.py", line 39, in <module>
nextbackenddocker_1 |     from next.api.resources.targets import Targets
nextbackenddocker_1 |   File "/next_backend/next/api/resources/targets.py", line 17, in <module>
nextbackenddocker_1 |     from next.api.widgets_library import widgetManager
nextbackenddocker_1 |   File "/next_backend/next/api/widgets_library/__init__.py", line 1, in <module>
nextbackenddocker_1 |     from widget_manager import widgetManager
nextbackenddocker_1 |   File "/next_backend/next/api/widgets_library/widget_manager.py", line 1, in <module>
nextbackenddocker_1 |     import next.apps.TupleBanditsPureExploration.widgets
nextbackenddocker_1 |   File "/next_backend/next/apps/TupleBanditsPureExploration/__init__.py", line 1, in <module>
nextbackenddocker_1 |     from .TupleBanditsPureExploration import *
nextbackenddocker_1 |   File "/next_backend/next/apps/TupleBanditsPureExploration/TupleBanditsPureExploration.py", line 23, in <module>
nextbackenddocker_1 |     from next.apps.TupleBanditsPureExploration.Dashboard import TupleBanditsPureExplorationDashboard
nextbackenddocker_1 |   File "/next_backend/next/apps/TupleBanditsPureExploration/Dashboard.py", line 15, in <module>
nextbackenddocker_1 |     import matplotlib.pyplot as plt
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 24, in <module>
nextbackenddocker_1 |     import matplotlib.colorbar
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/colorbar.py", line 29, in <module>
nextbackenddocker_1 |     import matplotlib.collections as collections
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/collections.py", line 23, in <module>
nextbackenddocker_1 |     import matplotlib.backend_bases as backend_bases
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 50, in <module>
nextbackenddocker_1 |     import matplotlib.textpath as textpath
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/textpath.py", line 11, in <module>
nextbackenddocker_1 |     import matplotlib.font_manager as font_manager
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1356, in <module>
nextbackenddocker_1 |     _rebuild()
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1343, in _rebuild
nextbackenddocker_1 |     pickle_dump(fontManager, _fmcache)
nextbackenddocker_1 |   File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 939, in pickle_dump
nextbackenddocker_1 |     with open(filename, 'wb') as fh:
nextbackenddocker_1 | IOError: [Errno 2] No such file or directory: '/tmp/matplotlib-root/fontList.cache'
nextbackenddocker_1 | [2015-10-30 16:20:11 +0000] [11] [INFO] Worker exiting (pid: 11)
nextbackenddocker_1 | [2015-10-30 16:20:12 +0000] [1] [DEBUG] 5 workers
nextbackenddocker_1 | [2015-10-30 16:20:13 +0000] [10] [INFO] Worker exiting (pid: 10)
nextbackenddocker_1 | [2015-10-30 16:20:13 +0000] [9] [INFO] Worker exiting (pid: 9)
nextbackenddocker_1 | [2015-10-30 16:20:13 +0000] [16] [INFO] Worker exiting (pid: 16)
nextbackenddocker_1 | [2015-10-30 16:20:14 +0000] [25] [INFO] Worker exiting (pid: 25)
nextbackenddocker_1 | [2015-10-30 16:20:14 +0000] [1] [INFO] Shutting down: Master
nextbackenddocker_1 | [2015-10-30 16:20:14 +0000] [1] [INFO] Reason: Worker failed to boot. 
```

**Comment by kgjamieson** [comment]
I can't reproduce this. I don't understand.
